- OpenFeature/build.gradle.kts
- build.gradle.kts
- release-please-config.json
- moves the definition of the group id and the version to the root gradle file
- set the group and version in the root since sonatype nexus gradle plugin wants it that way.
> build: define group and version in root build.gradle

- CONTRIBUTING.md
- adds documentations on how to release this library
Fixes #4
> docs: add release instructions

- .github/workflows/release_please.yaml
- Makes the maven-central release drop automatically when closed.
_To be merged when we know that the closing is successful._
> ci: change to closeAndRelease

- OpenFeature/src/main/java/dev/openfeature/sdk/Reason.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/exceptions/OpenFeatureError.kt
The standard error `TypeMismatch` has no exception in the SDK.
This PR exposes the exception.
> feat: Add new error for type mismatch

- OpenFeature/src/main/java/dev/openfeature/sdk/FlagEvaluationDetails.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/FlagEvaluationOptions.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/HookContext.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/ImmutableContext.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/ImmutableStructure.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/NoOpProvider.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/OpenFeatureClient.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/ProviderEvaluation.kt
- OpenFeature/src/test/java/dev/openfeature/sdk/HookSpecTests.kt
- OpenFeature/src/test/java/dev/openfeature/sdk/helpers/AlwaysBrokenProvider.kt
- OpenFeature/src/test/java/dev/openfeature/sdk/helpers/DoSomethingProvider.kt
Release-As: 0.1.0
- Changes a bunch of `var`s to `val`s
- Could definitely be considered a breaking change but since we're not at 1.0 I don't think we should bump major.
> refactor: changing vars to vals

- OpenFeature/src/main/java/dev/openfeature/sdk/EvaluationContext.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/ImmutableContext.kt
- OpenFeature/src/test/java/dev/openfeature/sdk/EvalContextTests.kt
- makes the targeting key in the immutable context truly immutable.
> refactor: make targeting key immutable

- OpenFeature/src/main/java/dev/openfeature/sdk/FeatureProvider.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/NoOpProvider.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/OpenFeatureAPI.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/async/AsyncClient.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/async/Extensions.kt
- OpenFeature/src/main/java/dev/openfeature/sdk/events/EventHandler.kt
- OpenFeature/src/test/java/dev/openfeature/sdk/EventsHandlerTest.kt
- OpenFeature/src/test/java/dev/openfeature/sdk/TestFeatureProvider.kt
- OpenFeature/src/test/java/dev/openfeature/sdk/helpers/AlwaysBrokenProvider.kt
- OpenFeature/src/test/java/dev/openfeature/sdk/helpers/DoSomethingProvider.kt
- README.md
- build.gradle.kts
- Make the eventing provider specific instead of being singleton
> feat: Make the eventing provider specific instead of being singleton

- android/src/main/java/dev/openfeature/sdk/async/Extensions.kt
- makes it possible to use `setProviderAndWait` and also pass the `EvaluationContext` in the same call.
> feat: set evaluation-context in setProviderAndWait()

- android/src/main/java/dev/openfeature/sdk/NoOpProvider.kt
- android/src/main/java/dev/openfeature/sdk/async/Extensions.kt
- android/src/main/java/dev/openfeature/sdk/events/EventHandler.kt
- android/src/main/java/dev/openfeature/sdk/events/OpenFeatureEvents.kt
- android/src/test/java/dev/openfeature/sdk/EventsHandlerTest.kt
- android/src/test/java/dev/openfeature/sdk/TestFeatureProvider.kt
- android/src/test/java/dev/openfeature/sdk/helpers/AlwaysBrokenProvider.kt
- android/src/test/java/dev/openfeature/sdk/helpers/DoSomethingProvider.kt
- Adds functionality to access the current status of the provider. 
Fixes #62
> feat: add getProviderStatus() function

- android/src/main/java/dev/openfeature/sdk/FeatureProvider.kt
- android/src/main/java/dev/openfeature/sdk/OpenFeatureAPI.kt
- android/src/main/java/dev/openfeature/sdk/async/Extensions.kt
- android/src/main/java/dev/openfeature/sdk/events/EventHandler.kt
- android/src/test/java/dev/openfeature/sdk/DeveloperExperienceTests.kt
- android/src/test/java/dev/openfeature/sdk/EventsHandlerTest.kt
- android/src/test/java/dev/openfeature/sdk/helpers/AlwaysBrokenProvider.kt
- android/src/test/java/dev/openfeature/sdk/helpers/SlowProvider.kt
`setContextAndWait` shouldn't hang if the Provider fails the initalization phase for some reason.
N/A
Similar logic will need to be added to setEvaluationContext 
Added unit tests
> fix: setProviderAndWait does not hang on ProviderError

- android/src/main/java/dev/openfeature/sdk/OpenFeatureAPI.kt
- android/src/main/java/dev/openfeature/sdk/async/Extensions.kt
- android/src/test/java/dev/openfeature/sdk/DeveloperExperienceTests.kt
- android/src/test/java/dev/openfeature/sdk/helpers/DoSomethingProvider.kt
- android/src/test/java/dev/openfeature/sdk/helpers/SlowProvider.kt
Update the `OpenFeatureAPI.observeEvents()` API:
- It can be called by the Application layer before any provider is configured, and it will still receive events once a new provider is configured and emitting events
- Thanks to this, we can now recommend setting up the observation before `setProvider` is called, thus ensuring no event from the configured provider is lost due to raciness between `observer` and `setProvider`
Usage example (from Application layer):
```
viewModelScope.launch {
OpenFeatureAPI.observeEvents().collect {
println(">> Event received: $it")
}
}
viewModelScope.launch {
OpenFeatureAPI.setProviderAndWait(
ConfidenceFeatureProvider.create(
app.applicationContext,
clientSecret
),
Dispatchers.IO,
ctx
)
}
> feat: Update observeEvents() API

- android/src/main/java/dev/openfeature/sdk/events/EventHandler.kt
- android/src/main/java/dev/openfeature/sdk/events/OpenFeatureEvents.kt
- android/src/test/java/dev/openfeature/sdk/EventsHandlerTest.kt
- android/src/test/java/dev/openfeature/sdk/TestFeatureProvider.kt
"NotReady" is not an [Event](https://openfeature.dev/specification/types#provider-status) yet in the Spec (but it is a [Status](https://openfeature.dev/specification/types#provider-status) as of the day of writing this PR). However, this transitional change is supposed to bring this implementation one step closer to the Spec (note that "ShutDown" is neither and "Event" nor a "Status"). This also brings the current implementation closer to the Swift implementation.
- https://github.com/open-feature/spec/issues/238
- https://github.com/open-feature/swift-sdk/pull/36
> refactor: Rename shutdown event to notready event

- README.md
- android/src/main/java/dev/openfeature/sdk/Client.kt
- android/src/main/java/dev/openfeature/sdk/FeatureProvider.kt
- android/src/main/java/dev/openfeature/sdk/ImmutableStructure.kt
- android/src/main/java/dev/openfeature/sdk/NoOpProvider.kt
- android/src/main/java/dev/openfeature/sdk/OpenFeatureClient.kt
- android/src/main/java/dev/openfeature/sdk/Tracking.kt
- android/src/main/java/dev/openfeature/sdk/TrackingEventDetails.kt
- android/src/test/java/dev/openfeature/sdk/TrackingProviderTests.kt
- adds support for tracking events as defined in the [spec](https://openfeature.dev/specification/sections/tracking).
Fixes #110
> feat: add support for tracking

- android/src/main/java/dev/openfeature/sdk/events/FeatureProviderExtensions.kt
- android/src/test/java/dev/openfeature/sdk/DeveloperExperienceTests.kt
- android/src/test/java/dev/openfeature/sdk/EventsHandlerTest.kt
- android/src/test/java/dev/openfeature/sdk/TestFeatureProvider.kt
- android/src/test/java/dev/openfeature/sdk/helpers/AutoHealingProvider.kt
- Fixes a crash where a Provider emits first an error event and then a ready event as part of the same `setProviderAndAwait()` call
Fixes #116 
This issue would also be solved when the `FeatureProvider.initialize` is a suspending function.
A test case was added which shows an example provider that had this crash.
> fix: Coroutine resume bug

- android/api/android.api
- android/build.gradle.kts
- build.gradle.kts
Adds the [binary-compatibility-validator plugin](https://github.com/Kotlin/binary-compatibility-validator) together with the current "spec" of the API.
This plugin will run as part of the gradle `check` phase and:
> The tool allows dumping binary API of a JVM part of a Kotlin library that is public in the sense of Kotlin visibilities and ensures that the public binary API wasn't changed in a way that makes this change binary incompatible.
The idea with this tool is that we can easily detect changes in the SDK API because the `./android/api/android.api` file will need to be updated in the PR that introduces the change.
This plugin will run as part of the CI and will validate all PRs.
When a deliberate API change is done, the "spec file" should be updated using 
```
./gradlew apiDump
``` …
> build: add plugin to validate api binary compatibility

- README.md
This addresses a linting issue when pulling the readme into the docs.
Relates to https://github.com/open-feature/kotlin-sdk/pull/124
> docs: add eventing section to read me

- README.md
- android/api/android.api
- android/build.gradle.kts
- android/src/main/java/dev/openfeature/sdk/FeatureProvider.kt
- android/src/main/java/dev/openfeature/sdk/OpenFeatureAPI.kt
- android/src/main/java/dev/openfeature/sdk/OpenFeatureClient.kt
- android/src/main/java/dev/openfeature/sdk/OpenFeatureStatus.kt
- android/src/main/java/dev/openfeature/sdk/events/OpenFeatureProviderEvents.kt
- android/src/test/java/dev/openfeature/sdk/DeveloperExperienceTests.kt
- android/src/test/java/dev/openfeature/sdk/FlagEvaluationsTests.kt
- android/src/test/java/dev/openfeature/sdk/HookSpecTests.kt
- android/src/test/java/dev/openfeature/sdk/HookSupportTests.kt
- android/src/test/java/dev/openfeature/sdk/OpenFeatureClientTests.kt
- android/src/test/java/dev/openfeature/sdk/ProviderEventingTests.kt
- android/src/test/java/dev/openfeature/sdk/StatusTests.kt
- android/src/test/java/dev/openfeature/sdk/TrackingProviderTests.kt
- android/src/test/java/dev/openfeature/sdk/helpers/AutoHealingProvider.kt
- android/src/test/java/dev/openfeature/sdk/helpers/BrokenInitProvider.kt
- android/src/test/java/dev/openfeature/sdk/helpers/DoSomethingProvider.kt
This PR brings back and enhances the possibility for providers to emit events which will then be handled by the SDK to set the SDK status.
> fix: bring back provider eventing

- android/src/test/java/dev/openfeature/sdk/DeveloperExperienceTests.kt
- android/src/test/java/dev/openfeature/sdk/StatusTests.kt
Fixing the test assertion and removing unnecessary schedule advances.
This manual test run shows the test suite is stable (50/50 runs) https://github.com/open-feature/kotlin-sdk/actions/runs/13660084832/job/38188994009.
> test: fix flaky test

- android/src/main/java/dev/openfeature/sdk/OpenFeatureAPI.kt
- android/src/test/java/dev/openfeature/sdk/StatusTests.kt
- Catches and ignores cancellation exceptions.
Since we call cancel manually when new providers or evaluation contexts are set it's a normal thing and it's just annoying if they show up as error statuses.
> fix: ignore cancellation exceptions

- android/api/android.api
- android/src/main/java/dev/openfeature/sdk/Hook.kt
- android/src/main/java/dev/openfeature/sdk/HookSupport.kt
- android/src/main/java/dev/openfeature/sdk/OpenFeatureClient.kt
- android/src/test/java/dev/openfeature/sdk/HookSupportTests.kt
- android/src/test/java/dev/openfeature/sdk/helpers/GenericSpyHookMock.kt
Adds evaluation deatils to finally hooks
Fixes #133
> feat!: add evaluation details fo finally hooks

- android/api/android.api
- android/src/main/java/dev/openfeature/sdk/ImmutableContext.kt
- android/src/main/java/dev/openfeature/sdk/ImmutableStructure.kt
- android/src/main/java/dev/openfeature/sdk/Value.kt
- android/src/test/java/dev/openfeature/sdk/DeepCopyTest.kt
- android/src/test/java/dev/openfeature/sdk/DeveloperExperienceTests.kt
- android/src/test/java/dev/openfeature/sdk/EvalContextTests.kt
- android/src/test/java/dev/openfeature/sdk/ImmutableContextTest.kt
- android/src/test/java/dev/openfeature/sdk/StructureTests.kt
- android/src/test/java/dev/openfeature/sdk/helpers/SpyProvider.kt
The ImmutableContext class was accepting mutable maps in its constructor, allowing callers to modify the original map after instantiation, which would affect the "immutable" context. This violated the immutability guarantee and could lead to unexpected behavior.
Implemented comprehensive deep immutability through defensive copying at all levels
Fixes #150
This change is backwards compatible at the API level. However if an integration was performing collection mutation for collections used in a context object, the behavior might now change.
> fix: Immutability of context
